/velodyne_transform_node:
  ros__parameters:
    model: VLP16
    calibration: /opt/ros/foxy/share/velodyne_pointcloud/params/VLP16db.yaml
    organize_cloud: false
    min_range: 0.3
    max_range: 100.0
